// Generated by CoffeeScript 1.7.1
(function() {
  var height, main, url, width, withData;

  url = 'http://feeds.delicious.com/v2/json/tags/dviramontes';

  width = 400;

  height = 200;

  withData = function(data) {
    return main(data);
  };

  $.ajax(url, {
    crossDomain: true,
    dataType: 'jsonp'
  }).error(function(xhr, status, error) {
    return alert(error.message);
  }).success(withData);

  main = function(data) {
    var group, svg, tags, theme;
    tags = _.map(data, function(d, i) {
      return {
        tag: i,
        "count": d
      };
    });
    theme = d3.scale.linear().domain([1, 20]).range(['#67001f', '#b2182b', '#d6604d', '#f4a582', "#fddbc7", "#ffffff", "#e0e0e0", "#bababa", "#878787", "#4d4d4d", "#1a1a1a"]);
    svg = d3.select('body').append('svg');
    svg.attr('width', width).attr('height', height).style({
      "border": "2px red solid"
    });
    group = svg.append('g').attr('transform', 'translate(' + 0 + ',' + height / 2 + ')');
    return group.selectAll('circle').data(tags).enter().append('circle').attr('cx', function(d, i) {
      return i;
    }).attr('cy', 0).attr('r', function(d, i) {
      return d.count;
    }).attr('fill', function(d, i) {
      return theme(i);
    });
  };

}).call(this);

//# sourceMappingURL=main.map
